export const accessTokenKey = "accessToken"
export const refreshTokenKey = "refreshToken"
export const signUpRoute = "/signup"
export const LoginRoute = "/login"
export const EditProfileRoute = "/edit_profile"
export const ChatRoomRoute = "/chat_room/:otherUsername"